FROM node:24-alpine

WORKDIR /app

COPY package*.json ./
RUN npm cache clean --force
RUN npm install --legacy-peer-deps

# Copy the source code
COPY . .

# Espone porta per React dev server
EXPOSE 3000

# Comando per dev: npm start (assumendo script in package.json: "start": "react-scripts start")
CMD ["npm", "start"]
