# Stage 1: Build
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
COPY ./config_sample.json ./config.json
COPY ./.air.toml ./.air.toml
# RUN CGO_ENABLED=0 GOOS=linux go build -o main .

# Stage 2: Dev runtime
FROM golang:1.25-alpine AS dev
WORKDIR /app
# Install Air for hot reload (optional but recommended for dev)
RUN go install github.com/air-verse/air@latest
# Copy source (override with volume in docker-compose for hot reload)
# COPY . .
# COPY ./config_sample.json ./config.json
# COPY --from=builder /app/.air.toml .
# Copy deps from builder
COPY --from=builder /go/pkg/mod /go/pkg/mod


# Per hot reload base (senza Air)
# CMD ["go", "run", ".", "./config_sample.json"]

# Per hot reload con Air (meglio!)
# RUN type air
# RUN cat ./.air.toml
CMD ["air", "-c", ".air.toml"]
